# Disable sudo to speed up the build
sudo: false

# Language and versions
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip

# Pip installs
install:
  - wget raw.github.com/gonzalo/gphoto2-updater/master/gphoto2-updater.sh
  - chmod 755 gphoto2-updater.sh
  - sudo ./gphoto2-updater.sh
  - sudo apt-get install cups libcups2-dev
  - sudo apt-get install python-opencv
  - sudo apt-get install python3-opencv
  - pip install pytest-benchmark
  - pip install pytest-cov
  - pip install -e .

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

# Run scripts
script:
  - pytest tests/ -v --cov pibooth/ --cov-report term

# Push the results back to codecov
after_success:
  - codecov

# Notification configuration
notifications:
  irc: false
  email: false
